### ISSUE TITLE
Cannot reproduce the classification accuracy on CIFAR-10 in the paper

### ISSUE THREAD

**Issue by WangyaqiAlly** [biuyq/CT-GAN#2]
Hi,
Thanks for sharing the code.  I am trying to reproduce the experiment on Cifar-10 in the paper by running CT_gan_cifar_resnet.py for 100000 iterations. But for the classification accuracy I just got 88.2%.  Is it because hyper parameters? Do you have any suggested hyperparameter setting to reproduce the experiment?

Thanks!

**Comment by biuyq** [comment]
@WangyaqiAlly Sorry for the delay. Did you run the CT_gan_cifar_resnet.py for reproducing the Inception score? Could you please show me the log you printed out in your terminal? Mine  is like this:

iter 99999	inception_50k_std	0.102137684822	acc_fake	0.96920311451	time	1.07430124044	dev_cost	0.406922727823	inception_50k	8.82567596436	cost	-0.300439655781	acgan	0.0241788756102	acc_real	1.0	wgan	-0.324618518353.

from where, the acc_fake (0.969) is what we mean the classification accuracy. 

BTW, all the codes we provided here are exactly what we did in our paper.

**Comment by WangyaqiAlly** [comment]
I misunderstood which one  the "Accuracy" in the table refer to. I thought it means the test accuracy on Cifar-10 test set . For the acc_fake, my result agree with this. 
Thanks so much for your reply and your accelent work.
